# 2.3 Lab: Introduction to Python

## Numerical Python

In [2]:
import numpy as np

In [3]:
x = np.array([3,4,5])
y = np.array([4,9,7])
x + y

array([ 7, 13, 12])

In [4]:
x  = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [5]:
x.ndim

2

In [6]:
x.dtype

dtype('int32')

In [7]:
x.shape

(2, 2)

In [8]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [9]:
x = np.array([1,2,3,4,5,6])
print(f"beginning x: {x}")
x_reshaped = x.reshape((2,3))
print(f"reshaped x: {x_reshaped}")

beginning x: [1 2 3 4 5 6]
reshaped x: [[1 2 3]
 [4 5 6]]


In [10]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [11]:
x**2

array([ 1,  4,  9, 16, 25, 36])

In [13]:
x = np.random.normal(size=50)
x

array([ 0.17310004,  0.01184071, -1.21332163,  0.84626534,  1.38230583,
       -1.1940635 ,  0.6030427 ,  0.13301434, -0.18255422,  0.81310457,
        0.4868659 , -0.23624462, -1.9687744 , -0.54372878,  1.82683622,
        1.31164939,  2.06427969, -0.47236902,  0.62924717,  1.55890746,
        0.06808659,  0.48179116,  1.75466596,  0.83643702, -0.6256396 ,
        0.34451103,  0.46930373,  1.08814369,  2.70686631, -0.73286458,
        0.44399907, -0.36960591, -0.28486238, -0.20693405, -0.15239188,
        0.61326397,  0.68590391, -1.43047372, -0.58185405, -0.68728419,
       -1.64560058, -0.36291356, -0.07234192,  1.67454113,  0.15846841,
        0.28001454, -0.45497199, -0.27008664, -0.9426287 , -0.25750827])

In [16]:
y = x + np.random.normal(loc=50,scale=1,size=50)
y

array([50.60949759, 50.32333504, 48.06119449, 51.12125193, 49.48703644,
       49.25363986, 50.37677071, 46.92629391, 48.99505145, 50.56771449,
       50.81784903, 48.81532974, 47.39487526, 49.57825105, 53.58932179,
       51.6938821 , 52.49514014, 48.16007036, 50.04864852, 49.45723793,
       49.92823585, 49.29352471, 52.7817933 , 51.86860152, 49.11481619,
       51.50650465, 50.8457191 , 51.29155078, 53.54399299, 49.50215193,
       50.18440511, 49.58230564, 49.16212967, 50.25667099, 47.27159201,
       52.63417555, 49.08356813, 49.13711108, 50.42746636, 50.18275635,
       47.93655979, 49.09870784, 50.57812999, 52.38315988, 53.34195947,
       49.84879783, 49.34382758, 50.25252213, 48.4018124 , 49.48044762])

In [17]:
np.corrcoef(x,y)

array([[1.        , 0.71681899],
       [0.71681899, 1.        ]])

## Pandas

In [18]:
import pandas as pd

In [32]:
Auto = pd.read_csv("data/Auto.csv")
Auto

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
392       1            ford mustang gl  
393       2                  vw pickup  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[397 rows x 9 columns]

In [23]:
Auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           397 non-null    float64
 1   cylinders     397 non-null    int64  
 2   displacement  397 non-null    float64
 3   horsepower    397 non-null    object 
 4   weight        397 non-null    int64  
 5   acceleration  397 non-null    float64
 6   year          397 non-null    int64  
 7   origin        397 non-null    int64  
 8   name          397 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.0+ KB


In [33]:
np.unique(Auto['horsepower'])

array(['100', '102', '103', '105', '107', '108', '110', '112', '113',
       '115', '116', '120', '122', '125', '129', '130', '132', '133',
       '135', '137', '138', '139', '140', '142', '145', '148', '149',
       '150', '152', '153', '155', '158', '160', '165', '167', '170',
       '175', '180', '190', '193', '198', '200', '208', '210', '215',
       '220', '225', '230', '46', '48', '49', '52', '53', '54', '58',
       '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70',
       '71', '72', '74', '75', '76', '77', '78', '79', '80', '81', '82',
       '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93',
       '94', '95', '96', '97', '98', '?'], dtype=object)

In [35]:
Auto['horsepower'].replace('?',np.nan,inplace=True)

In [36]:
Auto['horsepower'] = Auto['horsepower'].astype(np.float16)

In [37]:
np.unique(Auto['horsepower'])

array([ 46.,  48.,  49.,  52.,  53.,  54.,  58.,  60.,  61.,  62.,  63.,
        64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,  74.,  75.,
        76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,
        87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,
        98., 100., 102., 103., 105., 107., 108., 110., 112., 113., 115.,
       116., 120., 122., 125., 129., 130., 132., 133., 135., 137., 138.,
       139., 140., 142., 145., 148., 149., 150., 152., 153., 155., 158.,
       160., 165., 167., 170., 175., 180., 190., 193., 198., 200., 208.,
       210., 215., 220., 225., 230.,  nan], dtype=float16)

In [39]:
Auto.set_index("name")

mpg  cylinders  displacement  horsepower  weight  \
name                                                                           
chevrolet chevelle malibu  18.0          8         307.0       130.0    3504   
buick skylark 320          15.0          8         350.0       165.0    3693   
plymouth satellite         18.0          8         318.0       150.0    3436   
amc rebel sst              16.0          8         304.0       150.0    3433   
ford torino                17.0          8         302.0       140.0    3449   
...                         ...        ...           ...         ...     ...   
ford mustang gl            27.0          4         140.0        86.0    2790   
vw pickup                  44.0          4          97.0        52.0    2130   
dodge rampage              32.0          4         135.0        84.0    2295   
ford ranger                28.0          4         120.0        79.0    2625   
chevy s-10                 31.0          4         119.0        82.0    2720   

                           acceleration  year  origin  
name                                                   
chevrolet chevelle malibu          12.0    70       1  
buick skylark 320                  11.5    70       1  
plymouth satellite                 11.0    70       1  
amc rebel sst                      12.0    70       1  
ford torino                        10.5    70       1  
...                                 ...   ...     ...  
ford mustang gl                    15.6    82       1  
vw pickup                          24.6    82       2  
dodge rampage                      11.6    82       1  
ford ranger                        18.6    82       1  
chevy s-10                         19.4    82       1  

[397 rows x 8 columns]

In [41]:
idxs = ['mpg','horsepower','year']
Auto[idxs]

mpg  horsepower  year
0    18.0       130.0    70
1    15.0       165.0    70
2    18.0       150.0    70
3    16.0       150.0    70
4    17.0       140.0    70
..    ...         ...   ...
392  27.0        86.0    82
393  44.0        52.0    82
394  32.0        84.0    82
395  28.0        79.0    82
396  31.0        82.0    82

[397 rows x 3 columns]

In [44]:
Auto[Auto['year'] > 80][idxs]

mpg  horsepower  year
338  27.2        84.0    81
339  26.6        84.0    81
340  25.8        92.0    81
341  23.5       110.0    81
342  30.0        84.0    81
343  39.1        58.0    81
344  39.0        64.0    81
345  35.1        60.0    81
346  32.3        67.0    81
347  37.0        65.0    81
348  37.7        62.0    81
349  34.1        68.0    81
350  34.7        63.0    81
351  34.4        65.0    81
352  29.9        65.0    81
353  33.0        74.0    81
354  34.5         NaN    81
355  33.7        75.0    81
356  32.4        75.0    81
357  32.9       100.0    81
358  31.6        74.0    81
359  28.1        80.0    81
360  30.7        76.0    81
361  25.4       116.0    81
362  24.2       120.0    81
363  22.4       110.0    81
364  26.6       105.0    81
365  20.2        88.0    81
366  17.6        85.0    81
367  28.0        88.0    82
368  27.0        88.0    82
369  34.0        88.0    82
370  31.0        85.0    82
371  29.0        84.0    82
372  27.0        90.0    82
373  24.0        92.0    82
374  36.0        74.0    82
375  37.0        68.0    82
376  31.0        68.0    82
377  38.0        63.0    82
378  36.0        70.0    82
379  36.0        88.0    82
380  36.0        75.0    82
381  34.0        70.0    82
382  38.0        67.0    82
383  32.0        67.0    82
384  38.0        67.0    82
385  25.0       110.0    82
386  38.0        85.0    82
387  26.0        92.0    82
388  22.0       112.0    82
389  32.0        96.0    82
390  36.0        84.0    82
391  27.0        90.0    82
392  27.0        86.0    82
393  44.0        52.0    82
394  32.0        84.0    82
395  28.0        79.0    82
396  31.0        82.0    82